package com.example.parallaxliveapp.domain.model

import java.util.Date

/**
 * Represents a comment in a stream in the domain layer.
 *
 * @property id Unique identifier for the comment
 * @property streamId ID of the stream the comment belongs to
 * @property userId ID of the user who made the comment (null for system-generated comments)
 * @property username Username of the commenter
 * @property avatarUrl URL to the commenter's avatar (can be null)
 * @property text The comment content
 * @property timestamp When the comment was posted
 * @property reactions List of reactions to this comment (emoji codes)
 * @property isSystemGenerated Whether this comment was auto-generated by the system
 */
data class Comment(
    val id: String,
    val streamId: String,
    val userId: String? = null,
    val username: String,
    val avatarUrl: String? = null,
    val text: String,
    val timestamp: Date,
    val reactions: List<String> = emptyList(),
    val isSystemGenerated: Boolean = false
)